import "./globals.css";
import "react-tooltip/dist/react-tooltip.css";

import Nav from "./(components)/Nav";
import AuthProvider from "./(components)/AuthProvider";
import ToastProvider from "./(components)/toast-provider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <AuthProvider>
        <body className="bg-gray-50">
          <Nav />
          <div className="flex flex-col h-screen">
            <ToastProvider>{children}</ToastProvider>
          </div>
        </body>
      </AuthProvider>
    </html>
  );
}
